//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Rental.Web.App.DbDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public System.Guid Id { get; set; }
        public System.DateTime RentedAt { get; set; }
        public Nullable<System.DateTime> ReturnedAt { get; set; }
        public System.Guid VehicleId { get; set; }
        public System.Guid ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
