//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.WebApp.DbDiagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Counterparty> Counterparty { get; set; }
        public virtual DbSet<DeliveredMedicine> DeliveredMedicine { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<Sell> Sell { get; set; }
        public virtual DbSet<SoldMedicine> SoldMedicine { get; set; }
    }
}
