@startuml

title __REPOSITORY's Class Diagram__\n

  namespace com.vale.warehouses {
    namespace app.repository {
      interface com.vale.warehouses.app.repository.LeaseRequestRepository {
          {abstract} + findByLeasingContractIsNull()
          {abstract} + findByTenantIdAndLeasingContractIsNull()
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.repository {
      interface com.vale.warehouses.app.repository.LeasingContractRepository {
          {abstract} + findByOwnerId()
          {abstract} + findByOwnerIdAndLeasedTillAfter()
          {abstract} + findByOwnerIdAndLeasedTillBetweenOrderByLeasedTillDesc()
          {abstract} + findBySaleAgentId()
          {abstract} + findBySaleAgentIdAndLeasedAtBetween()
          {abstract} + findBySaleAgentIdAndLeasedTillAfter()
          {abstract} + findBySaleAgentIdAndLeasedTillBetweenOrderByLeasedTillDesc()
          {abstract} + findByWarehouseIdInAndLeasedTillAfterAndLeasedAtBeforeOrderByLeasedAtDesc()
          {abstract} + findByWarehouseIdInOrderByLeasedAtDesc()
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.repository {
      interface com.vale.warehouses.app.repository.OwnerRepository {
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.repository {
      interface com.vale.warehouses.app.repository.SaleAgentRepository {
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.repository {
      interface com.vale.warehouses.app.repository.TenantRepository {
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.repository {
      interface com.vale.warehouses.app.repository.WarehouseRepository {
          {abstract} + findByOwnerId()
          {abstract} + findBySaleAgentsId()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
