// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentimentWeb.Service.Data;

namespace SentimentWeb.Service.Data.Migrations
{
    [DbContext(typeof(SentimentWebContext))]
    [Migration("20201014201511_AddUserDataToCustomerFeedback")]
    partial class AddUserDataToCustomerFeedback
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SentimentWeb.Service.Data.Entities.CustomerFeedback", b =>
                {
                    b.Property<long>("Ident")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgeRange")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmedLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConfirmedSentiment")
                        .HasColumnType("bit");

                    b.Property<string>("InternalLangScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<bool>("SentToML")
                        .HasColumnType("bit");

                    b.Property<bool>("Sentiment")
                        .HasColumnType("bit");

                    b.Property<decimal>("SentimentProbability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SentimentScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ident");

                    b.ToTable("CustomerFeedbacks");
                });

            modelBuilder.Entity("SentimentWeb.Service.Data.Entities.MLInputFeedback", b =>
                {
                    b.Property<long>("Ident")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sentiment")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ident");

                    b.ToTable("MLInputFeedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
