//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Rental.Web.App.DbDiagram.UNI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestData_View
    {
        public string TestName { get; set; }
        public int QuestionCount { get; set; }
        public int QuestionVariations { get; set; }
        public string SubjectName { get; set; }
        public int Semester { get; set; }
        public string TeacherName { get; set; }
        public string FacultyName { get; set; }
        public string ClassName { get; set; }
        public System.Guid TestId { get; set; }
        public int Variant { get; set; }
        public int Number { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public bool IsCorrect { get; set; }
    }
}
