//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Rental.Web.App.DbDiagram.UNI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAtmptData_View
    {
        public System.Guid TestAttemptId { get; set; }
        public System.DateTime Date { get; set; }
        public string Subject { get; set; }
        public System.Guid TestId { get; set; }
        public string Test { get; set; }
        public System.Guid QuestionId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public bool IsCorrect { get; set; }
        public int TestSemester { get; set; }
        public string Teacher { get; set; }
        public string SubjectClass { get; set; }
        public string Faculty { get; set; }
        public string Student { get; set; }
        public string Email { get; set; }
        public string FacultyNumber { get; set; }
        public string StudentClass { get; set; }
    }
}
