@startuml

title __INTERFACES's Class Diagram__\n

  namespace com.vale.warehouses {
    namespace app.service {
      namespace interfaces {
        interface com.vale.warehouses.app.service.interfaces.LeaseRequestInterface {
            {abstract} + createLeaseRequest()
            {abstract} + deleteLeaseRequest()
            {abstract} + getLeaseRequest()
            {abstract} + getLeaseRequests()
            {abstract} + getLeaseRequestsWithoutContract()
            {abstract} + updateLeaseRequest()
        }
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.service {
      namespace interfaces {
        interface com.vale.warehouses.app.service.interfaces.LeasingContractInterface {
            {abstract} + createLeasingContract()
            {abstract} + deleteLeasingContract()
            {abstract} + getCurrentlyActiveLeasingContractsForOwner()
            {abstract} + getCurrentlyActiveLeasingContractsForSaleAgent()
            {abstract} + getEndingSoonLeasingContractsForOwner()
            {abstract} + getEndingSoonLeasingContractsForSaleAgent()
            {abstract} + getLeasingContract()
            {abstract} + getLeasingContracts()
            {abstract} + getLeasingContractsForOwner()
            {abstract} + getLeasingContractsForSaleAgent()
            {abstract} + getLeasingContractsForWarehouse()
            {abstract} + updateLeasingContract()
        }
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.service {
      namespace interfaces {
        interface com.vale.warehouses.app.service.interfaces.OwnerInterface {
            {abstract} + createOwner()
            {abstract} + deleteOwner()
            {abstract} + getOwner()
            {abstract} + getOwners()
            {abstract} + updateOwner()
        }
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.service {
      namespace interfaces {
        interface com.vale.warehouses.app.service.interfaces.RoleServiceInterface {
            {abstract} + getRoles()
        }
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.service {
      namespace interfaces {
        interface com.vale.warehouses.app.service.interfaces.SaleAgentInterface {
            {abstract} + createSaleAgent()
            {abstract} + deleteSaleAgent()
            {abstract} + getSaleAgent()
            {abstract} + getSaleAgents()
            {abstract} + updateSaleAgent()
        }
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.service {
      namespace interfaces {
        interface com.vale.warehouses.app.service.interfaces.TenantInterface {
            {abstract} + createTenant()
            {abstract} + deleteTenant()
            {abstract} + getTenant()
            {abstract} + getTenants()
            {abstract} + updateTenant()
        }
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.service {
      namespace interfaces {
        interface com.vale.warehouses.app.service.interfaces.UserServiceInterface {
            {abstract} + createUser()
            {abstract} + deleteUser()
            {abstract} + findByUsername()
            {abstract} + getUser()
            {abstract} + getUsers()
            {abstract} + updateUser()
        }
      }
    }
  }
  

  namespace com.vale.warehouses {
    namespace app.service {
      namespace interfaces {
        interface com.vale.warehouses.app.service.interfaces.WarehouseInterface {
            {abstract} + createWarehouse()
            {abstract} + deleteWarehouse()
            {abstract} + getWarehouse()
            {abstract} + getWarehouses()
            {abstract} + getWarehousesForOwner()
            {abstract} + getWarehousesForSaleAgent()
            {abstract} + updateWarehouse()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
