@startuml

title __LOGGEDIN's Class Diagram__\n

  namespace com.vale.warehouses {
    namespace ui.loggedin {
      class com.vale.warehouses.ui.loggedin.LoggedInActivity {
          - BadgeAboutToExpireLeases : TextView
          - BadgeCurrentlyLeasedWarehouses : TextView
          - BadgeLeaseRequests : TextView
          - RelativeLayoutAboutToExpireLeases : RelativeLayout
          - RelativeLayoutCurrentlyLeasedWarehouses : RelativeLayout
          - RelativeLayoutLeaseRequests : RelativeLayout
          - allWarehouses : List<Warehouse>
          - dateFrom : OffsetDateTime
          - dateTo : OffsetDateTime
          - editTextDateFrom : TextInputEditText
          - editTextDateTo : TextInputEditText
          - format : DateTimeFormatter
          - leaseRequests : List<String>
          - leasedWarehouses : List<Warehouse>
          - leasingContracts : List<LeasingContract>
          - listViewReportContractData : ListView
          - listViewReportWarehouseData : ListView
          - makeAnotherContractSearchButton : Button
          - makeAnotherWarehouseSearchButton : Button
          - roleId : int
          - saleAgentsSpinner : Spinner
          - searchContractsButton : Button
          - searchWarehousesButton : Button
          - textNotifications : TextView
          - usersButton : Button
          - warehouseContractsButton : Button
          - warehousesButton : Button
          + logout()
          + makeAnotherContractSearch()
          + makeAnotherWarehouseSearch()
          + onCreateOptionsMenu()
          + onOptionsItemSelected()
          + openLeasingContracts()
          + openUsers()
          + openWarehouses()
          + searchContractsForSaleAgent()
          + searchForFreeWarehouses()
          + showCurrentlyLeasedWarehouses()
          + showExpiredLeaseContracts()
          + showNewLeaseContractsRequests()
          # onCreate()
          - getAllCurrentlyLeasedWarehouses()
          - getAllNotCompletedLeaseRequests()
          - getClickListener()
          - getEndingSoonContracts()
          - handleAdminUser()
          - showDialog()
      }
    }
  }
  

  com.vale.warehouses.ui.loggedin.LoggedInActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.vale.warehouses.ui.loggedin.LoggedInActivity o-- com.vale.warehouses.service.view_model.LeaseRequestViewModel : leaseRequestViewModel
  com.vale.warehouses.ui.loggedin.LoggedInActivity o-- com.vale.warehouses.service.view_model.LeasingContractViewModel : leasingContractViewModel
  com.vale.warehouses.ui.loggedin.LoggedInActivity o-- com.vale.warehouses.service.view_model.SaleAgentViewModel : saleAgentViewModel
  com.vale.warehouses.ui.loggedin.LoggedInActivity o-- com.vale.warehouses.service.model.SaleAgent : selectedSaleAgent
  com.vale.warehouses.ui.loggedin.LoggedInActivity o-- com.vale.warehouses.ui.loggedin.LoggedInActivity : that
  com.vale.warehouses.ui.loggedin.LoggedInActivity o-- com.vale.warehouses.service.view_model.WarehouseViewModel : warehouseViewModel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
